### ISSUE TITLE
Upper case single-letter parameters seem to be broken by snake case

### ISSUE THREAD

**Issue by vraid** [scicloj/sklearn-clj#5]
Hi. I was trying out sklearn.regression/svr, and attempting to configure the parameters ran into the following error
```
Execution error at libpython-clj2.python.ffi/check-error-throw (ffi.clj:687).
TypeError: SVR.__init__() got an unexpected keyword argument 'c'
```

(reproduce through e.g `{:model-type :sklearn.regression/svr :C 1.0}`

This was the only parameter affected, and looking at the [sklearn documentation](https://scikit-learn.org/stable/modules/generated/sklearn.svm.SVR.html), it's also the only upper case parameter. The culprit behind the error seems to be that [sklearn-clj](https://github.com/scicloj/sklearn-clj/blob/main/src/scicloj/sklearn_clj.clj) transforms all parameters to lower case through snakify-keys.

There are other models with upper case parameters, and some models, like [svm l1_min_c](https://scikit-learn.org/stable/modules/generated/sklearn.svm.l1_min_c.html), even have both upper and lower case parameters (X and y).

It would be great if there's already a solution to this.
Otherwise, perhaps single letter parameters could be let through as-is, reserving snake case transformation for two letters or more?

Thanks in advance!

**Comment by behrica** [comment]
Thanks for reporting this.

Have you tried `{:model-type :sklearn.regression/svr "C" 1.0}` ?
As far as I remember the transformation acts on keywords.

**Comment by behrica** [comment]
I checked the code and indeed it assumes that all python estimators take all variables in "snake case", which  should start with a lowercase.
So in one way the "C" parameter violates this convention.
But it is  bug here and should be fixed.
